
#ifndef __Reflection_Ipc_h__

#define __Reflection_Ipc_h__

#include "Jc/ReflectionJc.h"
extern_C const ClassJc reflection_Address_InterProcessComm_s;
#define REFLECTION_Address_InterProcessComm_s &reflection_Address_InterProcessComm_s
extern_C const ClassJc reflection_InterProcessCommFactory_s;
#define REFLECTION_InterProcessCommFactory_s &reflection_InterProcessCommFactory_s
extern_C const ClassJc reflection_InterProcessComm_s;
#define REFLECTION_InterProcessComm_s &reflection_InterProcessComm_s
#endif // ___h__
