
#ifndef __Reflection_Fwc_h__

#define __Reflection_Fwc_h__

#include "Jc/ReflectionJc.h"
extern_C const ClassJc reflection_StacktraceElementJc;
#define REFLECTION_StacktraceElementJc &reflection_StacktraceElementJc
extern_C const ClassJc reflection_StacktraceThreadContext_s;
#define REFLECTION_StacktraceThreadContext_s &reflection_StacktraceThreadContext_s
extern_C const ClassJc reflection_ExceptionJc;
#define REFLECTION_ExceptionJc &reflection_ExceptionJc
extern_C const ClassJc reflection_TryObjectJc;
#define REFLECTION_TryObjectJc &reflection_TryObjectJc
extern_C const ClassJc reflection_StacktraceJc;
#define REFLECTION_StacktraceJc &reflection_StacktraceJc
extern_C const ClassJc reflection_ParseResultPrintfStyle_fwFormatter;
#define REFLECTION_ParseResultPrintfStyle_fwFormatter &reflection_ParseResultPrintfStyle_fwFormatter
extern_C const ClassJc reflection_LogMessageFW_i;
#define REFLECTION_LogMessageFW_i &reflection_LogMessageFW_i
extern_C const ClassJc reflection_ReadLine_Fwc;
#define REFLECTION_ReadLine_Fwc &reflection_ReadLine_Fwc
extern_C const ClassJc reflection_U_intfloat;
#define REFLECTION_U_intfloat &reflection_U_intfloat
extern_C const ClassJc reflection_U_ptr;
#define REFLECTION_U_ptr &reflection_U_ptr
extern_C const ClassJc reflection_Int32Array256;
#define REFLECTION_Int32Array256 &reflection_Int32Array256
extern_C const ClassJc reflection_FloatArray256;
#define REFLECTION_FloatArray256 &reflection_FloatArray256
extern_C const ClassJc reflection_FloatArray20;
#define REFLECTION_FloatArray20 &reflection_FloatArray20
extern_C const ClassJc reflection_ThreadContextFW_s;
#define REFLECTION_ThreadContextFW_s &reflection_ThreadContextFW_s
extern_C const ClassJc reflection_TimeBytes_Fwc;
#define REFLECTION_TimeBytes_Fwc &reflection_TimeBytes_Fwc
extern_C const ClassJc reflection_Va_listFW;
#define REFLECTION_Va_listFW &reflection_Va_listFW
extern_C const ClassJc reflection_ObjectJc;
#define REFLECTION_ObjectJc &reflection_ObjectJc
extern_C const ClassJc reflection_MtblHeadJc;
#define REFLECTION_MtblHeadJc &reflection_MtblHeadJc
#endif // ___h__
