
#ifndef __Reflection_AllJc_h__

#define __Reflection_AllJc_h__

#include "Jc/ReflectionJc.h"
extern_C const ClassJc reflection_AbstractCollectionJc;
#define REFLECTION_AbstractCollectionJc &reflection_AbstractCollectionJc
extern_C const ClassJc reflection_CharsetJc;
#define REFLECTION_CharsetJc &reflection_CharsetJc
extern_C const ClassJc reflection_ComparatorJc;
#define REFLECTION_ComparatorJc &reflection_ComparatorJc
extern_C const ClassJc reflection_Node_ConcurrentLinkedQueueJc;
#define REFLECTION_Node_ConcurrentLinkedQueueJc &reflection_Node_ConcurrentLinkedQueueJc
extern_C const ClassJc reflection_ConcurrentLinkedQueueJc_s;
#define REFLECTION_ConcurrentLinkedQueueJc_s &reflection_ConcurrentLinkedQueueJc_s
extern_C const ClassJc reflection_DateValuesJc;
#define REFLECTION_DateValuesJc &reflection_DateValuesJc
extern_C const ClassJc reflection_DateJc_s;
#define REFLECTION_DateJc_s &reflection_DateJc_s
extern_C const ClassJc reflection_SimpleDateFormatJc_s;
#define REFLECTION_SimpleDateFormatJc_s &reflection_SimpleDateFormatJc_s
extern_C const ClassJc reflection_TextFieldPositionJc_s;
#define REFLECTION_TextFieldPositionJc_s &reflection_TextFieldPositionJc_s
extern_C const ClassJc reflection_LocaleJc_s;
#define REFLECTION_LocaleJc_s &reflection_LocaleJc_s
extern_C const ClassJc reflection_SystemJc;
#define REFLECTION_SystemJc &reflection_SystemJc
extern_C const ClassJc reflection_ListItr_LinkedListJc;
#define REFLECTION_ListItr_LinkedListJc &reflection_ListItr_LinkedListJc
extern_C const ClassJc reflection_LinkedListJcD;
#define REFLECTION_LinkedListJcD &reflection_LinkedListJcD
extern_C const ClassJc reflection_LinkedListJc;
#define REFLECTION_LinkedListJc &reflection_LinkedListJc
extern_C const ClassJc reflection_ListJc;
#define REFLECTION_ListJc &reflection_ListJc
extern_C const ClassJc reflection_IteratorJc;
#define REFLECTION_IteratorJc &reflection_IteratorJc
extern_C const ClassJc reflection_ListMapEntryJc;
#define REFLECTION_ListMapEntryJc &reflection_ListMapEntryJc
extern_C const ClassJc reflection_HandleItem;
#define REFLECTION_HandleItem &reflection_HandleItem
extern_C const ClassJc reflection_OsWrapperJc_s;
#define REFLECTION_OsWrapperJc_s &reflection_OsWrapperJc_s
extern_C const ClassJc reflection_Access1TxData_ReflMemAccessJc;
#define REFLECTION_Access1TxData_ReflMemAccessJc &reflection_Access1TxData_ReflMemAccessJc
extern_C const ClassJc reflection_AccessTxData_ReflMemAccessJc;
#define REFLECTION_AccessTxData_ReflMemAccessJc &reflection_AccessTxData_ReflMemAccessJc
extern_C const ClassJc reflection_Access1RxData_ReflMemAccessJc;
#define REFLECTION_Access1RxData_ReflMemAccessJc &reflection_Access1RxData_ReflMemAccessJc
extern_C const ClassJc reflection_AccessRxData_ReflMemAccessJc;
#define REFLECTION_AccessRxData_ReflMemAccessJc &reflection_AccessRxData_ReflMemAccessJc
extern_C const ClassJc reflection_MemAccessDebugJc;
#define REFLECTION_MemAccessDebugJc &reflection_MemAccessDebugJc
extern_C const ClassJc reflection_MemAccessArrayDebugJc;
#define REFLECTION_MemAccessArrayDebugJc &reflection_MemAccessArrayDebugJc
extern_C const ClassJc reflection_FileJc_s;
#define REFLECTION_FileJc_s &reflection_FileJc_s
extern_C const ClassJc reflection_OutputStreamJc_s;
#define REFLECTION_OutputStreamJc_s &reflection_OutputStreamJc_s
extern_C const ClassJc reflection_FileOutputStreamJc_s;
#define REFLECTION_FileOutputStreamJc_s &reflection_FileOutputStreamJc_s
extern_C const ClassJc reflection_FileWriterJc_s;
#define REFLECTION_FileWriterJc_s &reflection_FileWriterJc_s
extern_C const ClassJc reflection_FileReaderJc_s;
#define REFLECTION_FileReaderJc_s &reflection_FileReaderJc_s
extern_C const ClassJc reflection_BufferedReaderJc_s;
#define REFLECTION_BufferedReaderJc_s &reflection_BufferedReaderJc_s
extern_C const ClassJc reflection_RunnableJc_s;
#define REFLECTION_RunnableJc_s &reflection_RunnableJc_s
extern_C const ClassJc reflection_ThreadJc_s;
#define REFLECTION_ThreadJc_s &reflection_ThreadJc_s
extern_C const ClassJc reflection_FormatterJc_s;
#define REFLECTION_FormatterJc_s &reflection_FormatterJc_s
extern_C const ClassJc reflection_TimeZoneJc_s;
#define REFLECTION_TimeZoneJc_s &reflection_TimeZoneJc_s
extern_C const ClassJc reflection_VaArgBuffer_Data_s;
#define REFLECTION_VaArgBuffer_Data_s &reflection_VaArgBuffer_Data_s
extern_C const ClassJc reflection_VaArgBuffer;
#define REFLECTION_VaArgBuffer &reflection_VaArgBuffer
#endif // ___h__
