
#ifndef __TimeSignals_Inspc_Refl_h__

#define __TimeSignals_Inspc_Refl_h__

#include "Jc/ReflectionJc.h"
extern_C const ClassJc reflection_Entry_TimeSignals_Inspc;
#define REFLECTION_Entry_TimeSignals_Inspc &reflection_Entry_TimeSignals_Inspc
extern_C const ClassJc reflection_Entries_TimeSignals_Inspc;
#define REFLECTION_Entries_TimeSignals_Inspc &reflection_Entries_TimeSignals_Inspc
extern_C const ClassJc reflection_TimeSignals_Inspc;
#define REFLECTION_TimeSignals_Inspc &reflection_TimeSignals_Inspc
#endif // ___h__
