
#ifndef __Reflection_Ipc_h__

#define __Reflection_Ipc_h__

#include "Jc/ReflectionJc.h"
extern const ClassJc reflection_Address_InterProcessComm_s;
#define REFLECTION_Address_InterProcessComm_s &reflection_Address_InterProcessComm_s
extern const ClassJc reflection_InterProcessCommFactory_i;
#define REFLECTION_InterProcessCommFactory_i &reflection_InterProcessCommFactory_i
extern const ClassJc reflection_InterProcessCommFactoryAccessor;
#define REFLECTION_InterProcessCommFactoryAccessor &reflection_InterProcessCommFactoryAccessor
extern const ClassJc reflection_InterProcessComm_i;
#define REFLECTION_InterProcessComm_i &reflection_InterProcessComm_i
#endif // ___h__
