
#ifndef __Reflection_Fwc_h__

#define __Reflection_Fwc_h__

#include "Jc/ReflectionJc.h"
extern const ClassJc reflection_StacktraceElementJc;
#define REFLECTION_StacktraceElementJc &reflection_StacktraceElementJc
extern const ClassJc reflection_StacktraceThreadContext_s;
#define REFLECTION_StacktraceThreadContext_s &reflection_StacktraceThreadContext_s
extern const ClassJc reflection_ExceptionJc;
#define REFLECTION_ExceptionJc &reflection_ExceptionJc
extern const ClassJc reflection_TryObjectJc;
#define REFLECTION_TryObjectJc &reflection_TryObjectJc
extern const ClassJc reflection_StacktraceJc;
#define REFLECTION_StacktraceJc &reflection_StacktraceJc
extern const ClassJc reflection_ParseResultPrintfStyle_fwFormatter;
#define REFLECTION_ParseResultPrintfStyle_fwFormatter &reflection_ParseResultPrintfStyle_fwFormatter
extern const ClassJc reflection_Int32Array256;
#define REFLECTION_Int32Array256 &reflection_Int32Array256
extern const ClassJc reflection_TimeBytes_Fwc;
#define REFLECTION_TimeBytes_Fwc &reflection_TimeBytes_Fwc
extern const ClassJc reflection_Va_listFW;
#define REFLECTION_Va_listFW &reflection_Va_listFW
extern const ClassJc reflection_LogMessageFW_i;
#define REFLECTION_LogMessageFW_i &reflection_LogMessageFW_i
extern const ClassJc reflection_ThreadContextFW_s;
#define REFLECTION_ThreadContextFW_s &reflection_ThreadContextFW_s
extern const ClassJc reflection_ObjectJc;
#define REFLECTION_ObjectJc &reflection_ObjectJc
extern const ClassJc reflection_MtblHeadJc;
#define REFLECTION_MtblHeadJc &reflection_MtblHeadJc
#endif // ___h__
